INSERT INTO STUDENT (NAME, GRADUATION_YEAR) VALUES ('Jim', 2007);
INSERT INTO STUDENT (NAME, GRADUATION_YEAR) VALUES ('Alex', 2012);
INSERT INTO STUDENT (NAME, GRADUATION_YEAR) VALUES ('Tim', 2002);
INSERT INTO STUDENT (NAME, GRADUATION_YEAR) VALUES ('Justin', 2009);
